/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcingRouteImport } from './routes/sourcing'
import { Route as ProspectionRouteImport } from './routes/prospection'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HunttoolRouteImport } from './routes/hunttool'
import { Route as CommunityManagerRouteImport } from './routes/community-manager'
import { Route as IndexRouteImport } from './routes/index'

const SourcingRoute = SourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionRoute = ProspectionRouteImport.update({
  id: '/prospection',
  path: '/prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HunttoolRoute = HunttoolRouteImport.update({
  id: '/hunttool',
  path: '/hunttool',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityManagerRoute = CommunityManagerRouteImport.update({
  id: '/community-manager',
  path: '/community-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-manager': typeof CommunityManagerRoute
  '/hunttool': typeof HunttoolRoute
  '/knowledge': typeof KnowledgeRoute
  '/prospection': typeof ProspectionRoute
  '/sourcing': typeof SourcingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-manager': typeof CommunityManagerRoute
  '/hunttool': typeof HunttoolRoute
  '/knowledge': typeof KnowledgeRoute
  '/prospection': typeof ProspectionRoute
  '/sourcing': typeof SourcingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-manager': typeof CommunityManagerRoute
  '/hunttool': typeof HunttoolRoute
  '/knowledge': typeof KnowledgeRoute
  '/prospection': typeof ProspectionRoute
  '/sourcing': typeof SourcingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-manager'
    | '/hunttool'
    | '/knowledge'
    | '/prospection'
    | '/sourcing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-manager'
    | '/hunttool'
    | '/knowledge'
    | '/prospection'
    | '/sourcing'
  id:
    | '__root__'
    | '/'
    | '/community-manager'
    | '/hunttool'
    | '/knowledge'
    | '/prospection'
    | '/sourcing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityManagerRoute: typeof CommunityManagerRoute
  HunttoolRoute: typeof HunttoolRoute
  KnowledgeRoute: typeof KnowledgeRoute
  ProspectionRoute: typeof ProspectionRoute
  SourcingRoute: typeof SourcingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sourcing': {
      id: '/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof SourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection': {
      id: '/prospection'
      path: '/prospection'
      fullPath: '/prospection'
      preLoaderRoute: typeof ProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunttool': {
      id: '/hunttool'
      path: '/hunttool'
      fullPath: '/hunttool'
      preLoaderRoute: typeof HunttoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-manager': {
      id: '/community-manager'
      path: '/community-manager'
      fullPath: '/community-manager'
      preLoaderRoute: typeof CommunityManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityManagerRoute: CommunityManagerRoute,
  HunttoolRoute: HunttoolRoute,
  KnowledgeRoute: KnowledgeRoute,
  ProspectionRoute: ProspectionRoute,
  SourcingRoute: SourcingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
